version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
      - JWT_SECRET=your_jwt_secret_here
      - GEMINI_API_KEY=your_gemini_api_key_here
      - NODE_ENV=production
      - PORT=5000
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: